server:
  port: 8081

spring:
  application:
    name: dubbo-client


# application.yml
dubbo:
  application:
    name: dubbo-client
  registry:
    address: N/A
  protocol:
    name: dubbo
    port: -1  # 客户端不需要占用端口
  consumer:
    check: false